name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-targets: true
          cache-on-failure: true
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Clippy (all features)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    name: Tests (stable)
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-targets: true
          cache-on-failure: true
      - name: Cargo test
        run: cargo test --workspace --all-features

  test-beta:
    name: Tests (beta)
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@beta
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-targets: true
          cache-on-failure: true
      - name: Cargo test
        run: cargo test --workspace --all-features
